### ISSUE TITLE
New source: Trustpilot

### ISSUE THREAD

**Issue by masyagin1998** [airbytehq/connector-contest#122]
Hello, Airbyte!

I'd like to work on Trustpilot connector, which can sync selected company reviews and tickets.
I can add additional streams, if they are needed right now for contest.

It doesn't need any API Key, because it uses direct Trustpilot website with little parsing.
I've talked about it here https://airbyte.com/blog/how-airbytes-reliable-ready-to-use-data-pipelines-sped-up-anecdotes-launch-and-growth and in Slack, and now I'm going to finally push it to open-source.

I think, it would be easier to implement it with Python HTTP Source SDK.

**Comment by masyagin1998** [comment]
@misteryeo
You said in Slack that I can tag You, when I start to work on connectors.

**Comment by misteryeo** [comment]
Please tag @RealChrisSean in future.

Similar to your other issue, why would it be easier to implement it with Python HTTP Source SDK? Is there a technical reason on this?

**Comment by RealChrisSean** [comment]
Good question @misteryeo. @masyagin1998 this will be easier to do with our low-code cdk since this may not require an API key. You can check out our docs [here](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/). But please try this using our low-code cdk for this hacktoberfest :). 

Here is a helpful [tutorial](https://www.youtube.com/watch?v=i7VSL2bDvmw) as well. Part 2 will go live later today. :)

**Comment by RealChrisSean** [comment]
@masyagin1998 I have also assigned this ticket to you.

**Comment by masyagin1998** [comment]
@RealChrisSean 
Thank You!

**Comment by RealChrisSean** [comment]
Labels have been added thank you :D
