### ISSUE TITLE
Source: Pendo.io

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/connector-contest#34]

**Comment by adayNU** [comment]
Was referred to https://www.pendo.io/partners/ - filled it out and waiting to hear back

**Comment by avaidyanatha** [comment]
Thanks for the update @adayNU!

**Comment by YiyangLi** [comment]
I'll work on this one!

**Comment by RealChrisSean** [comment]
Awesome this has been assigned to you. :)

**Comment by RealChrisSean** [comment]
Hi, @YiyangLi! How has it been going? Please let me know if there's anything we can assist you with :).

By the way, will you be using the [low-code CDK ](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/) for this? :)

**Comment by YiyangLi** [comment]
I plan to use the low-code CDK, just took off a pairing session with Brian Lai. He helped a lot and pointed me a good reference -- greenhouse. 

I am blocked currently on the pendo side. In order to use the API, I have to request an upgrade to unlock the integrations feature. Hopefully they can give me a 30-days free trial.

**Comment by RealChrisSean** [comment]
Hey @YiyangLi I'm happy to hear that Brian helped you out! Let us know if you still have a problem with that as we near the deadline. Good luck!

**Comment by YiyangLi** [comment]
![Screenshot 2022-10-28 at 1 52 05 PM](https://user-images.githubusercontent.com/6293908/198730428-62e94945-0df9-4ba1-8885-808c8aa25fac.png)

I have to give up the work on Pendo. In order to get the API key, I have to upgrade. 

I met the account executive in a zoom call. They can't just generate a key on a free account. I request an upgrade but I was rejected because I work for the direct competitor of Pendo (similar to Airbyte v.s. 5-tran). So the upgrade has to come from airbyte. 

Anyway, I am still happy to work on the connector, even if I miss the Octoberfest. It's challenging to upgrade, it's fun to use low-code, and it's requested a lot. I need your support @RealChrisSean @karenbajzaterlouw 
 
![Screenshot 2022-10-28 at 1 58 04 PM](https://user-images.githubusercontent.com/6293908/198731195-f7c99084-a59f-4d34-9ac5-27014ffe15bf.png)

**Comment by RealChrisSean** [comment]
Hi @YiyangLi I am so sorry to hear that. I will see if we can get an API for you. Unfortunately, I may not be able to get back to you until Monday or Tuesday with the weekend looming. As long as you submit ANY PR by or on 11/2, whether it is approved or not, you will have two weeks after 11/2 to have your PR merged.
