### ISSUE TITLE
Source: Microsoft Sharepoint

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/connector-contest#37]

**Comment by koskila** [comment]
This looks interesting - as long as you're interested in SharePoint Online (and not Server, i.e. on-prem) I'd be happy to take a shot at this! 😊

**Comment by avaidyanatha** [comment]
@koskila Yep I believe we're looking for Online! And awesome, it's yours!

**Comment by koskila** [comment]
Feel free to pass this on to someone else - the main part (integration to SharePoint Online) is very straightforward, but figuring out how to get everything else to work (using .NET on Docker on Windows) is a bit more than I can take on right now, since the current documentation is geared towards somewhat different scenarios.

I think it's fair to give the opportunity to someone else instead. :)

**Comment by armsepehr** [comment]
@RealChrisSean, why do you close the issue? The sharepoint connector is implemented or not in the mainline of the project
